framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            async_add_inventory:
                dsn: '%env(string:MESSENGER_TRANSPORT_DSN)%'
                options:
                    vhost: '%env(string:MESSENGER_VHOST)%'
                    exchange:
                        name: '%env(string:MESSENGER_EXCHANGE_ADD_INVENTORY)%'
                        type: direct
                    queues:
                        add_inventory_queue:
                            binding_keys: [ add_inventory_queue ]
            async_update_inventory:
                dsn: '%env(string:MESSENGER_TRANSPORT_DSN)%'
                options:
                    vhost: '%env(string:MESSENGER_VHOST)%'
                    exchange:
                        name: '%env(string:MESSENGER_EXCHANGE_UPDATE_INVENTORY)%'
                        type: direct
                    queues:
                        update_inventory_queue:
                            binding_keys: [ update_inventory_queue ]
            async_stock_out_mailer:
                dsn: '%env(string:MESSENGER_TRANSPORT_DSN)%'
                options:
                    vhost: '%env(string:MESSENGER_VHOST)%'
                    exchange:
                        name: '%env(string:MESSENGER_EXCHANGE_STOCK_OUT)%'
                        type: direct
                    queues:
                        mailer_stock_out_queue:
                            binding_keys: [ mailer_stock_out_queue ]
            failed:
                dsn: 'doctrine://default?queue_name=failed'
        routing:
            'App\Messenger\Message\UpdateInventoryMessage': async_update_inventory
            'App\Messenger\Message\AddInventoryMessage': async_add_inventory
            'App\Messenger\Message\NotificationStockOutMessage': async_stock_out_mailer